name: accounts_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  #? Core (Stage Management Network - Storage - Cache)
  dio: ^5.3.2
  hooks_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  flutter_hooks: ^0.20.1

  #? UI - View
  cupertino_icons: ^1.0.2
  shimmer: ^3.0.0

  #?Routing
  go_router: ^10.1.2

  #? Utilities
  logger: ^2.0.2
  mask_text_input_formatter: ^2.5.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  flutter_native_splash: ^2.3.2
  riverpod_generator: ^2.3.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

    # Enable generation of localized Strings from arb files.
  generate: true
